app-servicewp - prova iniziale OK - 30

diff --git a/0 b/0
--- a/0
+++ b/0
@@ -564,6 +564,33 @@ testnode() {
   echo "-------------------------------------------------------------- 5:"
   echo "TEST DA CONTROLLARE !!!"
   echo
+  echo "Verify nginx proxy is running ..."
+  curl 'localhost:8080/test.txt' > /dev/null 2>&1
+  GetTxt=$?
+  echo "Test result: ${GetTxt}"
+  echo
+  if [ $GetTxt -gt 0 ]
+  then
+    echo "nginx not running!"
+    echo "Please wait while I try to restart it"
+    echo
+    sudo docker-compose -f /home/pi/dockrepo/sysdata/raspi-test/raspi-test-nginx.yml up -d > /dev/null 2>&1
+    dots 2
+    curl 'localhost:8080/test.txt' > /dev/null 2>&1
+    GetTxt=$?
+    if [ $GetTxt -gt 0 ]
+    then
+      echo "nginx still NOT running"
+      echo 
+      echo "This error is not recoverable"
+      echo 
+      echo "Please retry section TEST or re-install docker"
+      pause
+      return 7
+    fi
+  fi
+  echo "nginx OK, continue ..."
+  echo
   echo
   echo "TEST - use docker-compose to run node js web servers"
   echo
@@ -617,6 +644,29 @@ testnode() {
   echo "pages above are dynamic and are generated by the respective"
   echo "node js servers, so you verify the node servers functioning"
   echo
+  pause
+}
+#
+##########################################################################
+link2doc() {
+# 6. link alla documentazione
+  echo 
+  echo 
+  echo 
+  echo 
+  echo 
+  echo "-------------------------------------------------------------- 5:"
+  echo "Links to documentation"
+  echo "    <-- right click to copy/open a link"
+  echo
+  echo "https://github.com/fpirri/gothings-raspi-install#readme"
+  echo "   <-- github repository README.md"
+  echo "https://www.gothings.org/raspberry-gothings/"
+  echo "   <-- raspberry doc from GoThings site"
+  echo "https://www.gothings.org/things/"
+  echo "   <-- GoThings documentation on the GoThings site"
+  echo
+  echo 
   pause
 }
 #
@@ -718,7 +768,7 @@ show_menus() {
   echo "3. COMPOSE    download & install docker-compose"
   echo "4. TEST       use docker-compose for a simple configuration"
   echo "5. TEST NODE  test node js express web servers"
-  echo "..."
+  echo "6. DOC        were to find documentation"
   echo "7. DELETE     delete all containers"
   echo "8. GoThings   download GoThings control menu"
   echo "9. TIMES      show elapsed times"
@@ -734,6 +784,7 @@ read_options(){
 		3) composeinstall;;
 		4) testgothings;;
     5) testnode;;
+    6) link2doc;;
     7) delconts;;
     8) gotocontrol;;
 		9) showtimes;;
